### ISSUE TITLE
classes known issues 

### ISSUE THREAD

**Issue by Cloze** [cooler-SAI/MopCore547#11]
here is the list of known bugs of classes which i tested by my self and confirm the issues.
i already started to fix the bugs and soon i will provide some fixes

**DK**
- [ ] Sudden Doom
- [ ] Anti-Magic Zone
- [ ] Blood Tap : you get the buff but cant use it
- [ ] Gargoyle : low damage
- [ ] Unholy Frenzy : will break cc
- [ ] Dark Simulacrum
___________

**Druid**
- [ ] Teleport : Moonglade
___________

**Hunter**
- [ ] Glyph of Black Ice
- [ ] Pet : attack on scatter
___________

**Mage**
- [ ] Critical Mass : extra chance more than blizzlike
- [ ] Alter Time : debuffs will be remove visually only for you target. but you can see them.
- [ ] Food : can use food on mount
___________

**Paladin**
- [ ] Divine Plea 
___________

**Priest**
- [ ] Spectral Guide 
- [ ] Power Word: Barrier 
___________

**Rogue**
- [ ] Vanish : debuffs and attacks cannot break vanish for 3 second. but it will.
- [ ] Subterfuge : totally not working. you just get the debuff
- [ ] Paralytic Poison : will trigger on 3 stack instead of 4
___________

**Shaman**
- [ ] Glyph of Totemic Vigor 
- [ ] Elemental Blast
___________

**Warlock**
- [ ] Demonic Circle : buff time
- [ ] Demonic Circle : not working
- [ ] Devour Magic
- [ ] Glyph of Felhunter
- [ ] Pet System : pet control is a mess
- [ ] Health Funnel
- [ ] Agony : do not get stack from malefic and the timing is broken
- [ ] Glyph of Gateway Attunement
___________

**Warrior**
- [ ] Seasoned Soldier
- [ ] Dragon Roar : damage is wrong
___________

i will provide more information about this issues soon.

**Comment by Ulduar** [comment]
Anti-Magic Zone 
Create Area Trigger (1193)

**Comment by cybrann** [comment]
Could you do a more detailed explanation for bugs on each spell? I cannot do any fixes without info and sadly I have no time to check for bugs myself.

**Comment by Keital** [comment]
same here, will close. @Cloze plz create an issue for each spell and follow issues templates from TC
