### ISSUE TITLE
Error MVS

### ISSUE THREAD

**Issue by Kudig** [cooler-SAI/MopCore547#12]
Всем привет и с Новым Годом!)
вот такие полезли после новых исправлений:
Ошибка	1	error C2653: Trinity: не является именем класса или пространства имен	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3800	1	scripts
Ошибка	2	error C2065: AnyUnfriendlyUnitInObjectRangeCheck: необъявленный идентификатор	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3800	1	scripts
Ошибка	3	error C2923: WoWSource::UnitListSearcher: "AnyUnfriendlyUnitInObjectRangeCheck" не является допустимым аргументом типа шаблон для параметра "Check"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3800	1	scripts
Ошибка	4	error C2514: WoWSource::UnitListSearcher: не имеет конструкторов	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3800	1	scripts
Ошибка	5	error C2039: IsAlive: не является членом "Unit"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3805	1	scripts
Ошибка	6	error C2653: Trinity: не является именем класса или пространства имен	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3838	1	scripts
Ошибка	7	error C2065: AnyUnfriendlyUnitInObjectRangeCheck: необъявленный идентификатор	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3838	1	scripts
Ошибка	8	error C2923: WoWSource::UnitListSearcher: "AnyUnfriendlyUnitInObjectRangeCheck" не является допустимым аргументом типа шаблон для параметра "Check"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3838	1	scripts
Ошибка	9	error C2514: WoWSource::UnitListSearcher: не имеет конструкторов	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3838	1	scripts
Ошибка	10	error C2039: IsAlive: не является членом "Unit"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3843	1	scripts
Ошибка	11	error C2653: Trinity: не является именем класса или пространства имен	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3876	1	scripts
Ошибка	12	error C2065: AnyUnfriendlyUnitInObjectRangeCheck: необъявленный идентификатор	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3876	1	scripts
Ошибка	13	error C2923: WoWSource::UnitListSearcher: "AnyUnfriendlyUnitInObjectRangeCheck" не является допустимым аргументом типа шаблон для параметра "Check"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3876	1	scripts
Ошибка	14	error C2514: WoWSource::UnitListSearcher: не имеет конструкторов	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3876	1	scripts
Ошибка	15	error C2039: IsAlive: не является членом "Unit"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3881	1	scripts
Ошибка	16	error C2653: Trinity: не является именем класса или пространства имен	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3914	1	scripts
Ошибка	17	error C2065: AnyUnfriendlyUnitInObjectRangeCheck: необъявленный идентификатор	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3914	1	scripts
Ошибка	18	error C2923: WoWSource::UnitListSearcher: "AnyUnfriendlyUnitInObjectRangeCheck" не является допустимым аргументом типа шаблон для параметра "Check"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3914	1	scripts
Ошибка	19	error C2514: WoWSource::UnitListSearcher: не имеет конструкторов	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3914	1	scripts
Ошибка	20	error C2039: IsAlive: не является членом "Unit"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3919	1	scripts
Ошибка	21	error C2653: Trinity: не является именем класса или пространства имен	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3952	1	scripts
Ошибка	22	error C2065: AnyUnfriendlyUnitInObjectRangeCheck: необъявленный идентификатор	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3952	1	scripts
Ошибка	23	error C2923: WoWSource::UnitListSearcher: "AnyUnfriendlyUnitInObjectRangeCheck" не является допустимым аргументом типа шаблон для параметра "Check"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3952	1	scripts
Ошибка	24	error C2514: WoWSource::UnitListSearcher: не имеет конструкторов	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3952	1	scripts
Ошибка	25	error C2039: IsAlive: не является членом "Unit"	C:\Work\MopCore547-master\src\server\scripts\Spells\spell_generic.cpp	3957	1	scripts

**Comment by Keital** [comment]
English pls

**Comment by Ulduar** [comment]
Partially error fix:
https://github.com/cooler-SAI/MopCore547/commit/11c94ee652a08cdff92e4c1cb3574d9c856dc71f
IsAlive replaced on isAlive.

**Comment by Ulduar** [comment]
@Kudig 
Try after https://github.com/cooler-SAI/MopCore547
Thanks and Happy New Year.

**Comment by Keital** [comment]
Fixed
