### ISSUE TITLE
GetHonorPoint - SetHonorPoint and manymore

### ISSUE THREAD

**Issue by Cloze** [cooler-SAI/MopCore547#14]
we dont have GetHonorPoint and SetHonorPoint anymore .
so how we can get the current player honorpoint ?

i mean not by using the query to database.
is there anyway ?

**Comment by cybrann** [comment]
Take a look on how it is implemented in TC and implement it here. It's orthodox Christmas so I don't have time, but I plan on updating this core because it is too outdated.

**Comment by Cloze** [comment]
Its implemented, but differently.
instead of GetHonorPoint should use GetCurrenct(CURRENCY_TYPE_HONOR_POINT, true) 
and for SetHonorPoint should use SetCurrency(CURRENCY_TYPE_HONOR_POINT, 100)
