### ISSUE TITLE
Arena states

### ISSUE THREAD

**Issue by Cloze** [cooler-SAI/MopCore547#15]
what we have now about the arena is character_arena_data.
old times we have arena_teams and other things to use inside our scripts
but now we have no idea what is going out there
is there any reference to use of ?
or is there any other things to use for getting the players arena states ? like the team names and types and the season ratings and MMR.

**Comment by cybrann** [comment]
In the Player class you have many functions that should return those values. Beware that in MoP arena teams do not exist anymore (I think). You have functions like: GetArenaPersonalRating, GetBestRatingOfWeek, GetBestRatingOfSeason, GetWeekWins, GetPrevWeekWins, GetSeasonWins, GetWeekGames, GetSeasonGames, GetArenaMatchMakerRating, GetMaxRating, GetMaxArenaRating.
And some others, I might have forgot to list them.

**Comment by Cloze** [comment]
@Ulduar its not a bug.

@cybrann your right. since we dont have teams as we knows it there is no such thing as arena_teams.

those function are working properly.
