### ISSUE TITLE
Cmake errors Ubuntu 16.04

### ISSUE THREAD

**Issue by Cubansephiroth** [cooler-SAI/MopCore547#16]
Maybe someone can help me with these.

wowtest@wowtest:~/MopCore547/build$ cmake ../ -DCMAKE_INSTALL_PREFIX=/home/wowtest/server -DWITH_WARNINGS=1
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- GCC: SFMT enabled, SSE2 flags forced
-- GCC: All warnings enabled
-- Found ACE library: /usr/lib/libACE.so
-- Found ACE headers: /usr/include
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so  
-- 
    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* TrinityCore rev. hash  : rev.1
* TrinityCore rev. date  : 2016-04-01 00:00:00 +0000
* TrinityCore buildtype  : Release

* Install core to        : /home/wowtest/server
* Install libraries to   : /home/wowtest/server/lib
* Install configs to     : /home/wowtest/server/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : No  (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show all warnings      : Yes
* Use coreside debug     : No  (default)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: Examples
  -> Prepared: Custom
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: The Maelstrom
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Pandaria
-- SCRIPT PREPARATION COMPLETE

-- Configuring done
CMake Error at src/server/scripts/CMakeLists.txt:150 (add_library):
  Cannot find source file:

    Outland/CoilfangReservoir/Underbog/boss_hungarfen.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "scripts".
CMake Error: CMake can not determine linker language for target: scripts
-- Generating done
-- Build files have been written to: /home/wowtest/MopCore547/build

**Comment by cooler-SAI** [comment]
sorry! only windows support

**Comment by Keital** [comment]
cooler i need owner access to the project to setup travisCI
