### ISSUE TITLE
DBC, VMaps, Maps

### ISSUE THREAD

**Issue by Effec7** [cooler-SAI/MopCore547#18]
Hi,

I am very impressed by your work guys, and thus I want to commend you. Also, I want to ask you, where can I find DBC, VMaps and Maps, since the link in the README file is broken, and extractors do not work for me.

Thank You!

Effec7

**Comment by boom8866** [comment]
Dbc, Maps, Mmaps and Vmaps can be found here: https://mega.nz/#!WBkllJDA!jInmVMyVg1HfpSRipsjamfsVLbUcg9EamcUcAENDxRI

**Comment by Effec7** [comment]
![image](https://cloud.githubusercontent.com/assets/3750469/21782282/256c97c8-d6b3-11e6-95cd-dd6e0d76b254.png)
This is what I get when I try to open up the link.

**Comment by alexkulya** [comment]
Try this:
https://mega.nz/#!oFAmXLQL!W-aGfJrsD5OPv5kIfB98Xp3bpmk8QD9kvtkThIeEXoI
or this:
https://github.com/cooler-SAI/MopCore547/releases/tag/mc547data
