### ISSUE TITLE
compilation_error 

### ISSUE THREAD

**Issue by Kudig** [cooler-SAI/MopCore547#19]
Error 1 error C2039: GetVictim: is not a member of the "Unit" C: \ Work \ MopCore547-master \ src \ server \ scripts \ Northrend \ Ulduar \ Ulduar \ boss_ignis.cpp 1 548 scripts
Error 2 error C2039: GetVictim: is not a member of the "Unit" C: \ Work \ MopCore547-master \ src \ server \ scripts \ Northrend \ Ulduar \ Ulduar \ boss_ignis.cpp 1 549 scripts

**Comment by Kudig** [comment]
GetVictim->getVictim

**Comment by Ulduar** [comment]
Fixed. Thanks.
