### ISSUE TITLE
Owner

### ISSUE THREAD

**Issue by Keital** [cooler-SAI/MopCore547#21]
@cooler-SAI  @alexkulya plz give me owner rights to repo to setup travis

**Comment by cooler-SAI** [comment]
only Collaborators here. It's need to create Organisation loke Jadecore was.

**Comment by alexkulya** [comment]
I do not have such rights. I am also an ordinary employee. :)
Attention. Divine Google translate.

**Comment by Keital** [comment]
@cooler-SAI well then i need you to setup travis in order to work in repo with such CI
