### ISSUE TITLE
Character Start screen problems

### ISSUE THREAD

**Issue by Cloze** [cooler-SAI/MopCore547#27]
There is some problems on character screen. 

1- when you create a new character for the second time it will not show you the new character until you relog or change realm. ( this is okay for the first character )
2- when you remove your character it will not refresh the list of the characters until you relog or change realm.
3- when you flag a player with RENAME, the player can change the name but it will freeze on "Updating name" and if you cancel it, it will show you the rename popup again. but if you relog or change rename you see that your name have changed.

option 3 can happen on change race and change faction too.

**Comment by Keital** [comment]
Probally just an opcode issue related to patched client being 5.4.8 and core 5.4.8

**Comment by cybrann** [comment]
It's a opcode problem, but it has no connection whatsoever to the version of the core or client. The core is 5.4.7 and the client is 5.4.7 it's just that client is edited using hexeditor to show that it's 5.4.8. Nothing else.
