### ISSUE TITLE
My JadeCore547 team

### ISSUE THREAD

**Issue by cooler-SAI** [cooler-SAI/MopCore547#3]
Dear team members. First of all thanks for your support on JadeCore, your fixes, advises. If you wanna continue make this core better ( it was originall 5.4.7 and we stay here), please write here.

@alexkulya , I send you invite.welcome, friend
https://github.com/cooler-SAI/MopCore547/invitations

**Comment by phulo** [comment]
im with you

**Comment by cooler-SAI** [comment]
@phulo  added you https://github.com/cooler-SAI/MopCore547/invitations
welcome back )

**Comment by darksoon** [comment]
me². can help to fix many sql`s... and test it online on my root ;)

**Comment by cooler-SAI** [comment]
@darksoon , added  you  https://github.com/cooler-SAI/MopCore547/invitations
feel free make fixes)))

**Comment by Keital** [comment]
cooler send me invite

**Comment by cooler-SAI** [comment]
@Keital , welcome, friend  https://github.com/cooler-SAI/MopCore547/invitations

**Comment by rSafari** [comment]
still looking for people ?

**Comment by Keital** [comment]
Sure, make a pull surelly cooler sends you an invite

**Comment by cooler-SAI** [comment]
@rSafari , added you https://github.com/cooler-SAI/MopCore547/invitations
welcome! P.S> and Happy New Year all!!!))))))

**Comment by cybrann** [comment]
@cooler-SAI I've got free time for fixes, if there is place on team ;)

**Comment by cooler-SAI** [comment]
@cybrann , sure,man! welcome)))  https://github.com/cooler-SAI/MopCore547/invitations

**Comment by enriqueppinf** [comment]
I would like to help testing core, could you invite me?

**Comment by cooler-SAI** [comment]
@enriqueppinf , make a pull for first commit, and I can add you

**Comment by alexkulya** [comment]
Андрей, нужно перевести этот репо в групповой репозиторий.

**Comment by cybrann** [comment]
@enriqueppinf If you would like to just test the core you do not need invitation, just compile and start testing.

**Comment by cooler-SAI** [comment]
@alexkulya , как это сделать?))

**Comment by alexkulya** [comment]
У тебя там должна быть опция, создать команду или что-то в этом роде. С JadeCore так делали.

**Comment by cooler-SAI** [comment]
а зачем создать? итак нормально всё - щас опять бардак будет - все разбегуться

**Comment by alexkulya** [comment]
Разбегаться то некому :)

**Comment by BrownFlower** [comment]
DBC, MAPs, etc. link is dead.

**Comment by alexkulya** [comment]
Link update

**Comment by Crypticaz** [comment]
looking to be invited

**Comment by doverman930** [comment]
Invite me to the team if you can that I am ready for empesar to work with this

**Comment by cooler-SAI** [comment]
@doverman930 ,already )))

**Comment by cooler-SAI** [comment]
@Crypticaz ,welcome

**Comment by Crypticaz** [comment]
Do you have a discord for this?

**Comment by cooler-SAI** [comment]
@Crypticaz , nope

**Comment by cooler-SAI** [comment]
so, all ,members from JadeCore return, I close it
