### ISSUE TITLE
Manual on Linux

### ISSUE THREAD

**Issue by mazdafil** [cooler-SAI/MopCore547#30]
En please give me instructions for installing on Linux. A-also what versions of the libraries, cmake and gcc required
Ru Дайте, пожалуйста, инструкцию по установке на Линукс. А также какие версии каких библиотек, cmake и gcc требуются

**Comment by cooler-SAI** [comment]
Sorry, only Win support

**Comment by mazdafil** [comment]
And instructions for Wlindows?

**Comment by cooler-SAI** [comment]
check trinitycore.info
