### ISSUE TITLE
Hello brother! Keep an eye on your core. But it hasn't been updated for a long time! I would like to ask you to update it?

### ISSUE THREAD

**Issue by a3396616601** [cooler-SAI/MopCore547#31]
Here's my test record for you
1，A large number of story tasks, or the use of task items, can not be completed!
2，Panda, 5 underground city, there is little downtime
3，Support for 5.4.7 plug-ins less!
These are my test results.
Hope you can see! My brothers are testing me.
If you need more test results to fix your core.
Please contact hezhujiao@163.com
I have bad English, these are the Google translation! I hope you can see
I'm sorry！

**Comment by cooler-SAI** [comment]
we know about issues, but don't have time forthis, fornow.keep an eye on project or try make fixes, and we will add all. thanks
