### ISSUE TITLE
CMake pretty source tree

### ISSUE THREAD

**Issue by cybrann** [cooler-SAI/MopCore547#35]
Looking for someone to implement pretty source tree in cmake, I don't know how, and It's pretty hard going trough files like it currently is in visual studio.

**Comment by Keital** [comment]
i did it in jadecore if im not wrong

**Comment by cybrann** [comment]
Could you do it here too? Jadecore repository is deleted and so I can't find commit just to take a look how it is done.

**Comment by cooler-SAI** [comment]
may be this can help https://github.com/cooler-SAI/JadeCore/commits/5.4.7

**Comment by Keital** [comment]
here @cybrann 
https://github.com/cooler-SAI/JadeCore/commit/e7f6bf7e37d7f701295eba4443a6bea80078eaed

**Comment by cybrann** [comment]
I added it already yesterday
