### ISSUE TITLE
Compile Error.

### ISSUE THREAD

**Issue by darksoon** [cooler-SAI/MopCore547#4]
hey there,
i have the problem that i cant compile the source :/ 
i used VS11 etc...  can compile the trinity source but this has 16 error:

`Warnung	1	warning C4018: '>': Konflikt zwischen 'signed' und 'unsigned'	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Spells\spell_mage.cpp	1209	1	scripts
Warnung	2	warning C4018: '<': Konflikt zwischen 'signed' und 'unsigned'	C:\Users\Administrator\Desktop\MopCore547\src\server\game\AI\SmartScripts\SmartScript.cpp	537	1	game
Fehler	3	error C2864: "boss_niuzao::boss_niuzaoAI::_charge33": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\WorldBosses\AugustCelestials\boss_niuzao.cpp	387	1	scripts
Fehler	4	error C2864: "boss_niuzao::boss_niuzaoAI::death": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\WorldBosses\AugustCelestials\boss_niuzao.cpp	388	1	scripts
Fehler	5	error C2864: "boss_chi_ji::boss_chi_jiAI::_children33": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\WorldBosses\AugustCelestials\boss_chi_ji.cpp	339	1	scripts
Fehler	6	error C2864: "boss_chi_ji::boss_chi_jiAI::death": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\WorldBosses\AugustCelestials\boss_chi_ji.cpp	340	1	scripts
Fehler	7	error C2864: "boss_xuen::boss_xuenAI::death": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\WorldBosses\AugustCelestials\boss_xuen.cpp	320	1	scripts
Fehler	8	error C2864: "boss_yu_lon::boss_yu_lonAI::death": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\WorldBosses\AugustCelestials\boss_yu_lon.cpp	381	1	scripts
Fehler	9	error C2864: "mob_jadefire_wall::mob_jadefire_wallAI::shouldTele": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\WorldBosses\AugustCelestials\boss_yu_lon.cpp	496	1	scripts
Fehler	10	error C2470: "apCaveBatPositions": Sieht wie eine Funktionsdefinition aus, es ist aber keine Parameterliste vorhanden; sichtbarer Funktionstext wird übersprungen.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\MogushanPalace\boss_trial_of_the_king.cpp	53	1	scripts
Fehler	11	error C2470: "pXinJumpPoint": Sieht wie eine Funktionsdefinition aus, es ist aber keine Parameterliste vorhanden; sichtbarer Funktionstext wird übersprungen.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\MogushanPalace\boss_trial_of_the_king.cpp	76	1	scripts
Fehler	12	error C2065: 'apCaveBatPositions': nichtdeklarierter Bezeichner	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\MogushanPalace\boss_trial_of_the_king.cpp	1245	1	scripts
Fehler	13	error C2065: 'apCaveBatPositions': nichtdeklarierter Bezeichner	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\MogushanPalace\boss_trial_of_the_king.cpp	1249	1	scripts
Fehler	14	error C2065: 'pXinJumpPoint': nichtdeklarierter Bezeichner	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\MogushanPalace\boss_trial_of_the_king.cpp	1441	1	scripts
Fehler	15	error C2864: "garrosh_hellscream_creature_iron_star::siege_of_orgrimmar_creaturesAI::m_Trigger": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\SiegeOfOrgrimmar\boss_garrosh_hellscream.cpp	2440	1	scripts
Fehler	16	error C2864: "garrosh_hellscream_creature_desecrated_weapon::siege_of_orgrimmar_creaturesAI::m_AreatriggerGUID": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\SiegeOfOrgrimmar\boss_garrosh_hellscream.cpp	2874	1	scripts
Fehler	17	error C2864: "garrosh_hellscream_creature_empowered_desecrated_weapon::siege_of_orgrimmar_creaturesAI::m_AreatriggerGUID": Nur statische konstante integrale Datenmember können innerhalb einer Klasse initialisiert werden.	C:\Users\Administrator\Desktop\MopCore547\src\server\scripts\Pandaria\SiegeOfOrgrimmar\boss_garrosh_hellscream.cpp	2996	1	scripts
Fehler	18	error LNK1104: Datei "..\scripts\Debug\scripts.lib" kann nicht geöffnet werden.	C:\Users\Administrator\Desktop\mop\src\server\worldserver\LINK	worldserver
`

**Comment by cooler-SAI** [comment]
Use VS 2013, I don't have any Errors on it

**Comment by mygithome002** [comment]
vs2013,win8.1...,lots of errors:
Error	16	error C1004: unexpected end-of-file found	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BastionOfTwilight\boss_council_of_ascendents.cpp	2118	1	scripts
Error	23	error C2065: 'roaringsummon' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackwingDescent\boss_atramedes.cpp	279	1	scripts
Error	28	error C2065: 'SAY_AGGRO' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_helix_gearbreaker.cpp	124	1	scripts
Error	38	error C2065: 'SAY_AGGRO' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_foereaper5000.cpp	170	1	scripts
Error	46	error C2065: 'SAY_AGGRO' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackrockCaverns\boss_corla_hearld_of_twilight.cpp	99	1	scripts
Error	51	error C2065: 'SAY_AGGRO' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackrockCaverns\boss_karsh_steelbender.cpp	74	1	scripts
Error	30	error C2065: 'SAY_DEATH' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_helix_gearbreaker.cpp	137	1	scripts
Error	41	error C2065: 'SAY_DEATH' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_foereaper5000.cpp	198	1	scripts
Error	47	error C2065: 'SAY_DEATH' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackrockCaverns\boss_corla_hearld_of_twilight.cpp	139	1	scripts
Error	52	error C2065: 'SAY_DEATH' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackrockCaverns\boss_karsh_steelbender.cpp	130	1	scripts
Error	29	error C2065: 'SAY_KILL' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_helix_gearbreaker.cpp	131	1	scripts
Error	39	error C2065: 'SAY_KILL' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_foereaper5000.cpp	181	1	scripts
Error	48	error C2065: 'SAY_KILL' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackrockCaverns\boss_corla_hearld_of_twilight.cpp	146	1	scripts
Error	53	error C2065: 'SAY_KILL' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackrockCaverns\boss_karsh_steelbender.cpp	137	1	scripts
Error	31	error C2065: 'SAY_OAF_DEAD' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_helix_gearbreaker.cpp	148	1	scripts
Error	32	error C2065: 'SAY_SPELL1' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_helix_gearbreaker.cpp	165	1	scripts
Error	37	error C2065: 'SAY_SPELL1' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_foereaper5000.cpp	144	1	scripts
Error	40	error C2065: 'SAY_SPELL2' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_foereaper5000.cpp	190	1	scripts
Error	36	error C2065: 'SAY_SPELL3' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_foereaper5000.cpp	133	1	scripts
Error	35	error C2065: 'SAY_SPELL4' : undeclared identifier	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_foereaper5000.cpp	121	1	scripts
Error	14	error C2143: syntax error : missing ';' before '{'	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BastionOfTwilight\boss_council_of_ascendents.cpp	237	1	scripts
Error	20	error C2181: illegal else without matching if	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackwingDescent\boss_maloriak.cpp	709	1	scripts
Error	13	error C2226: syntax error : unexpected type 'Position'	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BastionOfTwilight\boss_council_of_ascendents.cpp	236	1	scripts
Error	15	error C2447: '{' : missing function header (old-style formal list?)	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BastionOfTwilight\boss_council_of_ascendents.cpp	237	1	scripts
Error	27	error C2447: '{' : missing function header (old-style formal list?)	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_helix_gearbreaker.cpp	6	1	scripts
Error	34	error C2447: '{' : missing function header (old-style formal list?)	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\Deadmines\boss_foereaper5000.cpp	6	1	scripts
Error	45	error C2447: '{' : missing function header (old-style formal list?)	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackrockCaverns\boss_corla_hearld_of_twilight.cpp	6	1	scripts
Error	50	error C2447: '{' : missing function header (old-style formal list?)	E:\download\jadecore_souce\MopCore547-master\src\server\scripts\EasternKingdoms\BlackrockCaverns\boss_karsh_steelbender.cpp	5	1	scripts
...
...
