### ISSUE TITLE
invite request

### ISSUE THREAD

**Issue by Crypticaz** [cooler-SAI/MopCore547#41]
would love to help work on this core, looking for an invite

**Comment by alexkulya** [comment]
(EN)
You need to wait Cooler. He will give you the invitation.

(RU)
Нужно подождать Cooler. Он даст вам приглашение.

**Comment by doverman930** [comment]
I want to gang up with you to see if we do a nice job

**Comment by cooler-SAI** [comment]
hey all, @Crypticaz , @doverman930 , added you!
welcome, guys
https://github.com/cooler-SAI/MopCore547/invitations
please, accept invite

**Comment by doverman930** [comment]
I already am in I am unloading to BP trying and seeing that there is I throw tube before a mopcore but have a problems with the visual ones for example ursoc's vortex of the druid tapeworm problems with the visual just like the mushrooms not himself if that imitates tod that's why I displease enough that mopcore

**Comment by doverman930** [comment]
I would like to know if those errors are at present

**Comment by doverman930** [comment]
I would like to know if those errors are at present

**Comment by cooler-SAI** [comment]
@doverman930 , doesn't see this errors here,but you can fix whatever you want.Core or Database.
TODO here https://github.com/cooler-SAI/MopCore547/blob/master/docs/TODO.md, but you can edit this file

**Comment by Crypticaz** [comment]
I think a discord should be made for better communication @cooler-SAI it would help a lot

**Comment by doverman930** [comment]
Obvious man that fixes everything besides for that we are here to fix what he asks you to know if that continued why that it is something that the people that the spell have visual problems displeases but equal to this to take out me as good as possible we are going to take inside with all I like very much perfection
