### ISSUE TITLE
Siege of Orgrimmar & Throne of Thunder scripts

### ISSUE THREAD

**Issue by alexkulya** [cooler-SAI/MopCore547#7]
{EN}
In the near future it is necessary to transfer scripts for Dungeon: Siege of Orgrimmar and Throne of Thunder (From [JadeCore](https://github.com/JadeCore/JadeCore) source). Many thanks [Cybrann](https://github.com/cybrann) for the work done in these dungeons.
Please, do not delete the post until the migration. Thank you.

{RU}
В ближайшее время необходимо перенести скрипты для подземелий: Siege of Orgrimmar and Throne of Thunder (Из источника [JadeCore).](https://github.com/JadeCore/JadeCore) Огромное спасибо [Cybrann](https://github.com/cybrann) за проделанную работу по этим подземельям.
Просьба, пост не удалять, пока не выполним перенос. Спасибо.

SoO:
Dark Shamans: Migrate
General Nazgrim: Migrate
Malkorok: Migrate
Spoils of Pandaria: ---

ToT:
Durumu: Migrate
Primordius: ---
Dark Animus: ---

**Comment by cooler-SAI** [comment]
А что с заселением тестов? 
What about spawns?

**Comment by alexkulya** [comment]
Вчера тестироал локации. В общем, с заселением присутствуют проблемы, множественные дублированные спауны, неправильные местоположения некоторых НПС. Нужно править, и нужно больше тестов. Прогресс вписывать в отдельный файл. Одним словом, нужно больше активных сотрудников.

Warning! Google Translate.
Yesterday I test locations. In general, with the population there are problems, multiple duplicated spawn, wrong location of certain NPCs. It is necessary to rule, and we need more tests. Progress enter into a separate file. In short, the need of active employees.

**Comment by cooler-SAI** [comment]
Ну ничего! Москва ни сразу строилась)) сделаем.

No Problem! We can do it.

**Comment by alexkulya** [comment]
RU: Добавленные скрипты переходят в стадию "Тестирования"

EN: Added scripts transferred to the stage of "Test"

**Comment by cybrann** [comment]
I will do those scripts. I have fully scripted Throne of Thunder, everything except the bridge event.

**Comment by alexkulya** [comment]
Great job. As I said before, I appreciate your contribution to scripting of these dungeons.

**Comment by alexkulya** [comment]
Close. Repository JadeCore deleted.
